### PR TITLE
Add SlidesService

### PR DESCRIPTION
**Pull request by ddonnini**
Hi Tobias!
I've created a basic SlidesService, already using it in production, can you give it a look?

Thanks, see you in the other PR :+1: 

Daniele

### CODE REVIEW

**Comment by Nyholm** [comment]
Great. Thanks!

**Comment by ddonnini** [comment]
Thanks to you! Are you going to release a new tag?

**Comment by Nyholm** [comment]
Sure. Just tagged 2.3.0

**Comment by ddonnini** [comment]
Wonderful!

**Pull request merged**
