### PR TITLE
Introduced a new Service to manage GoogleSheets

### PR DESCRIPTION
**Pull request by giovannialbero1992**
This PR proposes to introduce a new feature to start to work with Google Sheets but takes some update on testsuite and on minimum-stable version.

This PR should be a start to a new major version of this bundle. 
Thanks

### CODE REVIEW

**Comment by giovannialbero1992** [comment]
Hi @Nyholm, can I close this PR or are you interested?

**Comment by Nyholm** [comment]
FYI @aschempp

**Comment by aschempp** [comment]
Thanks @giovannialbero1992! Some of the stuff seems pretty outdated after 2 years, are you still actively using that code?

**Comment by giovannialbero1992** [comment]
I don't know, I think that it is still used by @ddonnini

**Comment by ddonnini** [comment]
@aschempp yep, still used in production!

**Comment by giovannialbero1992** [comment]
@aschempp close it or merge it? :smile:

**Comment by aschempp** [comment]
I don't think it should be merged into the current state of the bundle, for two reasons:
 1. it would add a hard dependency on `reverse/g-sheets` even if one does not use Google Sheets
 2. it will raise the minimum requirement of `google/apiclient` to v2 (because `reverse/g-sheets` requires that), even though this bundle tries to be compatible with v1 as well.

Please keep it around, I'll try to set away some time to work on all of this. As discussed with @Nyholm (like a year ago 🤯 ) we should probably have a new major version of the bundle (with my other PRs and `google/apiclient` v2 only etc.). Unfortunately, the client I use this bundle for cancelled all budgets because of COVID, so I'll have to see for some free time for this.

**Pull request closed without merging**
